#@TYPE: Machine
#@NAME: Luckfox Pico Zero
#@SOC: Rockchip RV1106G3
#@DESCRIPTION: Machine configuration for Luckfox Pico Zero (eMMC) with Linux 6.6

require conf/machine/include/luckfox-rv1106.inc

KERNEL_DEVICETREE = "rockchip/rv1106g-luckfox-pico-zero.dtb"
RK_KERNEL_DTS_BASE = "rv1106g-luckfox-pico-zero"

IMAGE_FSTYPES = "wic ext4"
WKS_FILE = "luckfox-pico-zero.wks.in"

do_image_wic[depends] += "u-boot-rockchip:do_deploy virtual/kernel:do_deploy"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "rootfs-resize"
IMAGE_INSTALL:append = " luckfox-usb-gadget luckfox-vtx rockchip-mpp rockchip-rkaiq-server luckfox-iqfiles rockchip-camera-init"
